name: chucker_flutter
description: Chucker Flutter helps you inspect the HTTP(S) requests/responses. It stores data locally and provides a UI for inspecting network calls and sharing their content.
version: 1.8.3
repository: https://github.com/syedmurtaza108/chucker-flutter
issue_tracker: https://github.com/syedmurtaza108/chucker-flutter/issues
topics: [http, networking, chucker]
funding:
  - https://www.patreon.com/syedmurtaza

environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  chopper:
  dio:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http:
  share_plus:
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  http_mock_adapter:
  very_good_analysis:

screenshots:
  - description: Chucker Flutter Logo
    path: screenshots/logo.png
